### ISSUE TITLE
Add Course Content Types [3]

### ISSUE THREAD

**Issue by jwroche44** [jwroche44/LMS#3]
Once upon a time in a kingdom far away, there was a Teacher who wanted to have different types of course content but they couldn't because it didn't exist yet. They were very sad until one day an awesome engineer came to the kingdom's rescue and made it so that the Teacher can differentiate grading. The engineer received a raise and everyone lived happily ever after.

- [x] Create a table to contains available content types
- [x] Create the model for content type
- [x] Add foreign key to the course content table
- [x] Display the content type in the course view

**Comment by Jraymond** [comment]
Created the model and migration. table has id, courseid, and type as columns. courseid is a foreign key

**Comment by Jraymond** [comment]
I may have lied jeff, im getting an error when I try to migrate the tables (that i didn't get before) some general syntax error in "create table 'content_types' (primary key) ". I looked though things as best I could but it all looked fine to me. let me know if you spot something, otherwise ill keep looking online for stuff

**Comment by jwroche44** [comment]
@Jraymond What is your branch?

**Comment by Jraymond** [comment]
ok all fixed now it migrates. I didnt get the chance to seed it but the seeder itself is set up
